### PR TITLE
Added initial support for TZWP-100 (Smart Switch).

### PR DESCRIPTION
**Pull request by mickem**
Only support for on/off so no power-meter and no config (feel free to add it)

Please note that the icon is displayed wrong no idea why it looks good in chrome and inkscape...

### CODE REVIEW

**Comment by yhaugom** [comment]
@mickem Thank you for your contribution! 
Next time you could try using the [http://pngtosvg.com/](http://pngtosvg.com/) online converter. 
Also make sure the images is of the correct size. See [Athom Developer pages](https://developer.athom.com/docs/apps/tutorial-App%20Store.html) for documentation.
I have changed the icons and resized the images.

**Comment by yhaugom** [comment]
@mickem 
Could you please point me to where you have seen the support for these capabilities 
`"meter_power",  "measure_power", "measure_current", "measure_voltage"`
All I can find is this:
"Association Group Information V1 
Association V2
Basic V1
Binary Switch V1
Configuration V2
Device Reset Local V1
Firmware Update MD V2
Manufacturer Specific V1
Powerlevel 
Protection V2"

**Comment by mickem** [comment]
I have no clue, no nothing about neither z-wave not homey...

I simply read "Power level" here (https://products.z-wavealliance.org/products/1536/classes )  which I assumed was measurement for power...
Feel free to remove it...

**Comment by yhaugom** [comment]
Ok, I see. Think that is something else.
You can read about the Z-wave specifications here: http://zwavepublic.com/specifications

Powerlevel is mentioned here: http://zwavepublic.com/sites/default/files/command_class_specs_2017A/SDS13784-5%20Z-Wave%20Network-Protocol%20Command%20Class%20Specification.pdf

“The Powerlevel Command Class defines RF transmit power controlling Commands useful when installing or testing a network. The Commands makes it possible for supporting controllers to set/get the RF transmit power level of a node and test specific links between nodes with a specific RF transmit power level.

NOTE: This Command Class is only used in an installation or test situation.”


I’ve removed it, and have committed it to my master branch on github, but I need to fix some errors in settings for it to be approved on the Homey App Store. Think it is errors in magnet contact sensor settings. More strict control after update of cli, wich is nice, but I don’t understand my errors yet.

Yngve

Fra: Michael Medin <notifications@github.com>
Sendt: 3. april 2018 07:50
Til: yhaugom/com.telldus <com.telldus@noreply.github.com>
Kopi: Yngve Haugom <yngve_haugom@hotmail.com>; State change <state_change@noreply.github.com>
Emne: Re: [yhaugom/com.telldus] Added initial support for TZWP-100 (Smart Switch). (#3)


I have no clue, no nothing about neither z-wave not homey...

I simply read "Power level" here (https://products.z-wavealliance.org/products/1536/classes ) which I assumed was measurement for power...
Feel free to remove it...

**Pull request merged**
