### PR TITLE
New icon.svg for TZWP-102

### PR DESCRIPTION
**Pull request by marcus-karlsson**
Original icon become a tiny dot in App, replaced with larger icon

### CODE REVIEW

**Comment by JohanBendz** [comment]
Hmm, not sure that version of the icon will be OK everywhere. If needed I include one that should be ok.

[icon.zip](https://github.com/yhaugom/com.telldus/files/2942972/icon.zip)

**Comment by marcus-karlsson** [comment]
@JohanBendz  Commited your file to the pull request instead. Tested it and it works fine.
I do not know guidelines for creating these icon files. 
What is the trick to creating an icon that will have a universal fit on all platforms? 
I did not understand why the original icon came out so small in the first place..
Thanks

**Comment by JohanBendz** [comment]
The trick is to use a tool that writes a fully compatible svg file and a proved/original Athom icon.svg file as template. I use Microsoft Inkscape, it's free on Microsoft Store.

**Comment by marcus-karlsson** [comment]
I was using incscape but then I will start with an icon from athom next time. Thanks!On Mar 7, 2019 22:52, Johan Bendz <notifications@github.com> wrote:The trick is to use a tool that writes a fully compatible svg file and a proved/original Athom icon.svg file as template. I use Microsoft Inkscape, it's free on Microsoft Store.

**Pull request merged**
